
//auth
const SIGN_IN_URL: string = '/auth/sign-in';

//admin
const ADMIN_URL: string = '/dashboard';
const ADMIN_NOTIFICATIONS_URL: string = `${ADMIN_URL}/notifications`;
const ADMIN_MERCHANTS_URL: string = `${ADMIN_URL}/merchants`;
const ADMIN_MERCHANTS_ADD_URL: string = `${ADMIN_MERCHANTS_URL}/add-merchant`;
const ADMIN_MERCHANTS_TRANSACTION_URL: string = `${ADMIN_MERCHANTS_URL}/transactions`;

//admin customers
const ADMIN_CUSTOMERS_URL: string = `${ADMIN_URL}/customers`;
const ADMIN_CUSTOMERS_ADD_URL: string = `${ADMIN_CUSTOMERS_URL}/add-customer`;
const ADMIN_CUSTOMERS_TRANSACTION_URL: string = `${ADMIN_CUSTOMERS_URL}/transactions`;


const ADMIN_MERCHANTS_REPORTS_URL: string = `${ADMIN_MERCHANTS_URL}/reports`;
const ADMIN_MERCHANTS_LOGS_URL: string = `${ADMIN_MERCHANTS_URL}/logs`;
const ADMIN_MERCHANTS_ROLES_URL: string = `${ADMIN_URL}/roles`;

const ADMIN_CHARITY_URL: string = `${ADMIN_URL}/charity`;
const ADMIN_CHARITY_ADD_URL: string = `${ADMIN_CHARITY_URL}/add-charity`;

const ADMIN_DEALS_PROMO_URL: string = `${ADMIN_URL}/deals-promo`;
const ADMIN_DEALS_PROMO_ADD_URL: string = `${ADMIN_DEALS_PROMO_URL}/add-deal-promo`;

const ADMIN_MANAGEMENT_URL: string = `${ADMIN_URL}/admin-management`;
const ADMIN_MANAGEMENT_ADD_URL: string = `${ADMIN_MANAGEMENT_URL}/add-admin`;

const ADMIN_ACTIVITY_LOGS_URL: string = `${ADMIN_URL}/activity-logs`;

const ADMIN_REPORTS_URL: string = `${ADMIN_URL}/reports`;
const ADMIN_REPORTS_POINTS_URL: string = `${ADMIN_REPORTS_URL}/points-report`;
const ADMIN_REPORTS_CHARITY_URL: string = `${ADMIN_REPORTS_URL}/charity-report`;


export { ADMIN_ACTIVITY_LOGS_URL, ADMIN_CHARITY_ADD_URL, ADMIN_CHARITY_URL, ADMIN_CUSTOMERS_ADD_URL, ADMIN_CUSTOMERS_TRANSACTION_URL, ADMIN_CUSTOMERS_URL, ADMIN_DEALS_PROMO_ADD_URL, ADMIN_DEALS_PROMO_URL, ADMIN_MANAGEMENT_ADD_URL, ADMIN_MANAGEMENT_URL, ADMIN_MERCHANTS_ADD_URL, ADMIN_MERCHANTS_LOGS_URL, ADMIN_MERCHANTS_REPORTS_URL, ADMIN_MERCHANTS_ROLES_URL, ADMIN_MERCHANTS_TRANSACTION_URL, ADMIN_MERCHANTS_URL, ADMIN_NOTIFICATIONS_URL, ADMIN_REPORTS_CHARITY_URL, ADMIN_REPORTS_POINTS_URL, ADMIN_REPORTS_URL, ADMIN_URL, SIGN_IN_URL };

