
//auth
const SIGN_IN_URL: string = '/auth/sign-in';

//admin
const ADMIN_URL: string = '/dashboard';
const ADMIN_NOTIFICATIONS_URL: string = `${ADMIN_URL}/notifications`;
const ADMIN_MERCHANTS_URL: string = `${ADMIN_URL}/merchants`;
const ADMIN_MERCHANTS_ADD_URL: string = `${ADMIN_MERCHANTS_URL}/add-merchant`;
const ADMIN_MERCHANTS_POS_BRANCH_URL: string = `${ADMIN_MERCHANTS_URL}/add-pos-branch`;
const ADMIN_MERCHANTS_POS_BRANCH_LIST_URL: string = `${ADMIN_MERCHANTS_URL}/pos-branch`;
const ADMIN_MERCHANTS_TRANSACTION_URL: string = `${ADMIN_URL}/merchants/transactions`;
const ADMIN_TRANSACTIONS_URL: string = `${ADMIN_URL}/transactions`;
const ADMIN_FUNDING_URL: string = `${ADMIN_TRANSACTIONS_URL}/funding`;
const ADMIN_TRANSACTIONS_PURCHASES_URL: string = `${ADMIN_TRANSACTIONS_URL}/purchases`;
const ADMIN_TRANSACTIONS_PAYOUTS_URL: string = `${ADMIN_TRANSACTIONS_URL}/payouts`;
const ADMIN_TRANSACTIONS_POINTS_URL: string = `${ADMIN_TRANSACTIONS_URL}/points`;
const ADMIN_TRANSACTIONS_WALLETS_URL: string = `${ADMIN_TRANSACTIONS_URL}/wallets`
//admin customers
const ADMIN_CUSTOMERS_URL: string = `${ADMIN_URL}/customers`;
const ADMIN_CUSTOMERS_ADD_URL: string = `${ADMIN_CUSTOMERS_URL}/add-customer`;
const ADMIN_CUSTOMERS_TRANSACTION_URL: string = `${ADMIN_CUSTOMERS_URL}/transactions`;


const ADMIN_MERCHANTS_REPORTS_URL: string = `${ADMIN_MERCHANTS_URL}/reports`;
const ADMIN_MERCHANTS_LOGS_URL: string = `${ADMIN_MERCHANTS_URL}/logs`;
const ADMIN_MERCHANTS_ROLES_URL: string = `${ADMIN_URL}/roles`;
const ADMIN_SIGN_UP_BONUS_URL: string = `${ADMIN_URL}/bonus/get-bonus`;
const ADMIN_SIGN_UP_BONUS_ADD_URL: string = `${ADMIN_URL}/bonus/add-bonus`;

const ADMIN_CHARITY_URL: string = `${ADMIN_URL}/charity`;
const ADMIN_CHARITY_ADD_URL: string = `${ADMIN_CHARITY_URL}/add-charity`;
const ADMIN_CHARITY_TRANSACTION_URL: string = `${ADMIN_CHARITY_URL}/transactions`;

const ADMIN_DEALS_PROMO_URL: string = `${ADMIN_URL}/deals-promo`;
const ADMIN_DEALS_PROMO_ADD_URL: string = `${ADMIN_DEALS_PROMO_URL}/add-deal-promo`;
const ADMIN_DEALS_PROMO_SPONSORED_DEAL_URL: string = `${ADMIN_DEALS_PROMO_URL}/sponsored-deal`;
const ADMIN_DEALS_PROMO_SPONSORED_DEAL_ADD_URL: string = `${ADMIN_DEALS_PROMO_URL}/add-sponsored-deal`;
const ADMIN_MANAGEMENT_URL: string = `${ADMIN_URL}/admin-management`;
const ADMIN_MANAGEMENT_ADD_URL: string = `${ADMIN_MANAGEMENT_URL}/add-admin`;

const ADMIN_ACTIVITY_LOGS_URL: string = `${ADMIN_URL}/activity-logs`;

const ADMIN_REPORTS_URL: string = `${ADMIN_URL}/reports`;
const ADMIN_REPORTS_POINTS_URL: string = `${ADMIN_REPORTS_URL}/points-report`;
const ADMIN_REPORTS_CHARITY_URL: string = `${ADMIN_REPORTS_URL}/charity-report`;
const ADMIN_REPORTS_SUPPORT_URL: string = `${ADMIN_URL}/support`;


export { ADMIN_ACTIVITY_LOGS_URL, ADMIN_CHARITY_ADD_URL, ADMIN_CHARITY_TRANSACTION_URL, ADMIN_CHARITY_URL, ADMIN_CUSTOMERS_ADD_URL, ADMIN_CUSTOMERS_TRANSACTION_URL, ADMIN_CUSTOMERS_URL, ADMIN_DEALS_PROMO_ADD_URL, ADMIN_DEALS_PROMO_SPONSORED_DEAL_ADD_URL, ADMIN_DEALS_PROMO_SPONSORED_DEAL_URL, ADMIN_DEALS_PROMO_URL, ADMIN_FUNDING_URL, ADMIN_MANAGEMENT_ADD_URL, ADMIN_MANAGEMENT_URL, ADMIN_MERCHANTS_ADD_URL, ADMIN_MERCHANTS_LOGS_URL, ADMIN_MERCHANTS_POS_BRANCH_LIST_URL, ADMIN_MERCHANTS_POS_BRANCH_URL, ADMIN_MERCHANTS_REPORTS_URL, ADMIN_MERCHANTS_ROLES_URL, ADMIN_MERCHANTS_TRANSACTION_URL, ADMIN_MERCHANTS_URL, ADMIN_NOTIFICATIONS_URL, ADMIN_REPORTS_CHARITY_URL, ADMIN_REPORTS_POINTS_URL, ADMIN_REPORTS_SUPPORT_URL, ADMIN_REPORTS_URL, ADMIN_SIGN_UP_BONUS_ADD_URL, ADMIN_SIGN_UP_BONUS_URL, ADMIN_TRANSACTIONS_PAYOUTS_URL, ADMIN_TRANSACTIONS_POINTS_URL, ADMIN_TRANSACTIONS_PURCHASES_URL, ADMIN_TRANSACTIONS_URL, ADMIN_TRANSACTIONS_WALLETS_URL, ADMIN_URL, SIGN_IN_URL };

